### ISSUE TITLE
2024bw抢票老闪退，提示

### ISSUE THREAD

**Issue by XiChenBaBa** [Just-Prog/Bilibili_show_ticket_auto_order#22]
正在尝试第: 1次抢票
请求超时 请检查网络
HTTP Error 429: Too Many Requests
Traceback (most recent call last):
  File "main.py", line 21, in <module>
  File "api.py", line 658, in start
  File "api.py", line 335, in orderCreate
  File "api.py", line 330, in checkAvaliable
TypeError: 'NoneType' object is not subscriptable
[29292] Failed to execute script 'main' due to unhandled exception!

**Comment by Bi2Nb9O3-Studio** [comment]
同问

**Comment by Emiyaplaymaker** [comment]
> 正在尝试第： 1次抢票 请求超时 请检查网络 HTTP 错误 429：请求过多 回溯（最近一次调用）：文件“main.py”，第 21 行，在文件“api.py”中，第 658 行，在开始中 文件“api.py”，第 335 行，在 orderCreate 文件“api.py”，第 330 行，在检查中 Avaliable TypeError：“NoneType”对象不可下标 [29292] 由于未处理的异常，无法执行脚本“main”！

同问

**Comment by Congregalis** [comment]
https://show.bilibili.com/api/ticket/project/getV2 这个api触发风控了。。作者没有判断就直接闪退了

**Comment by Emiyaplaymaker** [comment]
> https://show.bilibili.com/api/ticket/project/getV2 这个api触发风控了。。作者没有判断就直接闪退了

那循环的问题如何解决呢

**Comment by Bi2Nb9O3-Studio** [comment]
```python
Traceback (most recent call last):
  File "C:\Bi2Nb9O3\Software\ticket_auto_order_x64_v1.10.1_PG (2)\main.py", line 21, in <module>
    Api(proxies=proxies,specificID=specificID,sleepTime=sleep,token=token).start()
  File "C:\Bi2Nb9O3\Software\ticket_auto_order_x64_v1.10.1_PG (2)\api.py", line 658, in start
    if self.orderCreate():
       ^^^^^^^^^^^^^^^^^^
  File "C:\Bi2Nb9O3\Software\ticket_auto_order_x64_v1.10.1_PG (2)\api.py", line 438, in orderCreate
    self.tokenGet()
  File "C:\Bi2Nb9O3\Software\ticket_auto_order_x64_v1.10.1_PG (2)\api.py", line 275, in tokenGet
    (msg, validate) = click.verify(gt, challenge, w)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: bili_ticket极验模块错误 { 错误类型: MissingParam("validate") }
```
还有个这个问题

**Comment by Congregalis** [comment]
> > https://show.bilibili.com/api/ticket/project/getV2 这个api触发风控了。。作者没有判断就直接闪退了
> 
> 那循环的问题如何解决呢

判断下没有data就继续循环吧。但是被风控限制了应该一段时间内就没法抢了，只能换代理ip继续了，比较麻烦
