### ISSUE TITLE
bili-ticket-gt module error: `MissingParam("Validate")`

### ISSUE THREAD

**Issue by ParticleG** [Just-Prog/Bilibili_show_ticket_auto_order#35]
```log
Traceback (most recent call last):
  File "C:\Users\particleg\Programming\PycharmProjects\Bilibili_show_ticket_auto_order\api.py", line 227, in geetestPass
    (msg, validate) = click.verify(gt, challenge, w)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: bili_ticket极验模块错误 { 错误类型: MissingParam("validate") }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\particleg\Programming\PycharmProjects\Bilibili_show_ticket_auto_order\api.py", line 216, in geetestPass
    (c, s) = slide.get_c_s(gt, challenge)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: bili_ticket极验模块错误 { 错误类型: MissingParam("data") }
```

**Comment by Just-Prog** [comment]
降级到1.10.3试下

**Comment by ParticleG** [comment]
> 降级到1.10.3试下

尝试直接从源码运行不存在这个问题，只有exe存在这个问题，目前尚不明确原因

**Comment by ParticleG** [comment]
目前存在的另一个问题，当Token过期重新获取时会出现`MissingParam("data")`
```log
HTTP Error 412: Precondition Failed
正在尝试第: 1334次抢票
请求超时 请检查网络
HTTP Error 412: Precondition Failed
正在尝试第: 1335次抢票
2024-07-06 19:53:27 (LT) Token已过期! 正在重新获取
=== 发现验证 ===
click
Geetest自动化检测出错。错误代码：bili_ticket极验模块错误 { 错误类型: Other("验证码自查出现错误") }
Geetest自动化检测出错。错误代码：bili_ticket极验模块错误 { 错误类型: MissingParam("data") }
Geetest自动化检测出错。错误代码：bili_ticket极验模块错误 { 错误类型: MissingParam("data") }
Geetest自动化检测出错。错误代码：bili_ticket极验模块错误 { 错误类型: MissingParam("data") }
Geetest自动化检测出错。错误代码：bili_ticket极验模块错误 { 错误类型: MissingParam("data") }
```

**Comment by ParticleG** [comment]
Also this:
```log
=== 发现验证 ===
配置文件内预留验证手机号码与要求不符，请在此重新输入:
```
这玩意无论输入什么都不行（

**Comment by Wangxiaolu0716** [comment]
> Also this:
> ```log
> === 发现验证 ===
> 配置文件内预留验证手机号码与要求不符，请在此重新输入:
> ```
> 这玩意无论输入什么都不行（

+1

**Comment by linger6580** [comment]
> Also this:
> 
> ```
> === 发现验证 ===
> 配置文件内预留验证手机号码与要求不符，请在此重新输入:
> ```
> 
> 这玩意无论输入什么都不行（

我也遇到这个问题！

**Comment by Just-Prog** [comment]
> > 降级到1.10.3试下
> 
> 尝试直接从源码运行不存在这个问题，只有exe存在这个问题，目前尚不明确原因

这玩意属于偶发型故障，重开修复几率挺高的

**Comment by Just-Prog** [comment]
> Also this:
> 
> ```
> === 发现验证 ===
> 配置文件内预留验证手机号码与要求不符，请在此重新输入:
> ```
> 
> 这玩意无论输入什么都不行（

字符串匹配写烂了，私密马赛
